### ISSUE TITLE
forward_url not working

### ISSUE THREAD

**Issue by Arsur** [jjlawren/python-plexauth#1]
I tried to set this up with forward_url which gives me something like

https://app.plex.tv/auth#!?clientID=clientID&code=pinID&forwardUrl=https%3A%2F%2Fexample.com

But the link is not working as intended. I am on the right page for 1ms, until getting redirected to plex.tv with the following error:
> 
> We were unable to complete this request.
> You will be redirected automatically.

**Comment by jjlawren** [comment]
This was working until somewhere around Nov 3rd when Plex hardened the security a bit. You'll need to use the latest release of the library and pass in an 'Origin' header that matches the protocol & domain of the `forwardUrl` param:
```
payload = { ... }
headers = {"Origin": "https://example.com" }
plexauth = PlexAuth(payload, headers=headers)
```
I believe they did this to ensure the client isn't redirected to anywhere besides the original requester of the auth flow.
